---
- name: Průběžně obměňovaný playbook
  hosts: "{{ seznam_stanic }}"
  tasks: 
   - name: Zakáže updaty
     win_command: sc stop wuauserv
     ignore_errors: yes
      
   - name: Zakáže autostart updatů
     win_command: sc config wuauserv start= disabled
     ignore_errors: yes
     
   - name: Kontrola instalace chocolatey
     win_command: choco
     register: result
     ignore_errors: yes
     
   - name: install_chocolatey
     win_chocolatey:
      name: "chocolatey"
      state: downgrade
      version: 0.10.11
     when: result is failed    
     
     
  
