---
- name: Průběžně obměňovaný playbook
  hosts: "{{ seznam_stanic }}"
  tasks: 
   - name: Zakáže updaty
     win_command: sc stop wuauserv
     ignore_errors: yes
      
   - name: Zakáže autostart updatů
     win_command: sc config wuauserv start= disabled
     ignore_errors: yes
     
 #  - name: Kontrola instalace chocolatey
 #    win_command: choco
 #    register: result
 #    ignore_errors: yes
 #    
 #  - name: instalace chocolatey (pokud není)
 #    
     #unfinished
     
   - name: instalace fontů
     win_copy: 
      src: "{{ cesta_src1 }}"
      dest: "{{ cesta_dest1 }}"
      remote_src: yes
     vars: 
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: "{{ superucet }}"
      ansible_become_pass: "{{ superheslo }}"
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only 
   
   - name: instalace fontů
     win_copy: 
      src: "{{ cesta_src2 }}"
      dest: "{{ cesta_dest2 }}"
      remote_src: yes
     vars: 
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: "{{ superucet }}"
      ansible_become_pass: "{{ superheslo }}"
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
   
   - name: instalace fontů
     win_copy: 
      src: "{{ cesta_src3 }}"
      dest: "{{ cesta_dest3 }}"
      remote_src: yes
     vars: 
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: "{{ superucet }}"
      ansible_become_pass: "{{ superheslo }}"
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
      
   - name: instalace fontů
     win_copy: 
      src: "{{ cesta_src4 }}"
      dest: "{{ cesta_dest4 }}"
      remote_src: yes
     vars: 
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: "{{ superucet }}"
      ansible_become_pass: "{{ superheslo }}"
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
      
   - name: instalace fontů
     win_copy: 
      src: "{{ cesta_src5 }}"
      dest: "{{ cesta_dest5 }}"
      remote_src: yes
     vars: 
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: "{{ superucet }}"
      ansible_become_pass: "{{ superheslo }}"
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
            
   - name: instalace fontů
     win_copy: 
      src: "{{ cesta_src6 }}"
      dest: "{{ cesta_dest6 }}"
      remote_src: yes
     vars: 
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: "{{ superucet }}"
      ansible_become_pass: "{{ superheslo }}"
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
            
   - name: instalace fontů
     win_copy: 
      src: "{{ cesta_src7 }}"
      dest: "{{ cesta_dest7 }}"
      remote_src: yes
     vars: 
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: "{{ superucet }}"
      ansible_become_pass: "{{ superheslo }}"
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
            
   - name: instalace fontů
     win_copy: 
      src: "{{ cesta_src8 }}"
      dest: "{{ cesta_dest8 }}"
      remote_src: yes
     vars: 
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: "{{ superucet }}"
      ansible_become_pass: "{{ superheslo }}"
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
            
   - name: instalace fontů
     win_copy: 
      src: "{{ cesta_src9 }}"
      dest: "{{ cesta_dest9 }}"
      remote_src: yes
     vars: 
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: "{{ superucet }}"
      ansible_become_pass: "{{ superheslo }}"
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
            
   - name: instalace fontů
     win_copy: 
      src: "{{ cesta_src10 }}"
      dest: "{{ cesta_dest10 }}"
      remote_src: yes
     vars: 
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: "{{ superucet }}"
      ansible_become_pass: "{{ superheslo }}"
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
